languageCode = "en-us"
title = "Beloved"
baseURL = "https://my-beloved.github.io/"
theme = "hugo-theme-massively"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[languages]
[languages.en]
  languageName = "English"


