baseURL = 'http://example.org/'
languageCode = 'en-us' 
theme = 'graysx' 
title = 'Beloved by Toni Morrison' ## Site Settings [params]
[params]
logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"

# Info
address = "South View Cemetery, Atlanta, Fulton County, Georgia, USA"
email = "chloe.anthony.wofford@gmail.com"
phone = "609-279-0343"

# Socials

twitter = "https://twitter.com/tonimorrrison?lang=en"
facebook = "https://www.facebook.com/OfficialToniMorrisonAuthor/"
github = "https://github.com/my-beloved/my-beloved.github.io"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projects"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#signup"
  weight = 3


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04
